name: Test ALL vulnerability findings

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images: [ "ghcr.io/chainguard-dev/nginx:1.19", "ghcr.io/chainguard-dev/vulhub/nginx:1.13.2", "ghcr.io/chainguard-dev/vulhub/activemq:5.11.1" ]

    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
    - name: Run Scans
      uses: strongjz/actions/vul-scans@0c5fce04aac33ea47f537a053b9a6d0d9aaa861b
      id: scans
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        image: ${{ matrix.images }}
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        RUN_SNYK: "true"
        UPLOAD_GITHUB_CODE: "true"

    - name: Image Vunability scan output
      env:
        SNYK_COUNT: ${{ steps.scans.outputs.SNYK_COUNT }}
        GRYPE_COUNT: ${{ steps.scans.outputs.GRYPE_COUNT }}
        TRIVY_COUNT: ${{ steps.scans.outputs.TRIVY_COUNT }}
      run: |
        echo "Image Vulnerability scan output" >> $GITHUB_STEP_SUMMARY
        echo "Image ID: ${{ matrix.images }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Snyk Count: $SNYK_COUNT" >> $GITHUB_STEP_SUMMARY
        echo "Grype Count: $GRYPE_COUNT" >> $GITHUB_STEP_SUMMARY
        echo "Trivy Count: $TRIVY_COUNT" >> $GITHUB_STEP_SUMMARY

    - name: Send Scan report
      if: ${{ steps.scans.outputs.TRIVY_COUNT != '0' || steps.scans.outputs.GRYPE_COUNT != '0' || steps.scans.outputs.SNYK_COUNT != '0'  }}
      uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
      env:
        SLACK_ICON: http://github.com/chainguardian.png?size=48
        SLACK_USERNAME: chainguardian
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: james-test-channel
        SLACK_COLOR: '#8E1600'
        MSG_MINIMAL: 'false'
        SLACK_TITLE: Vulnerability Report for ${{ github.repository }}.
        SLACK_MESSAGE: |
          Snyk Count: ${{ steps.scans.outputs.SNYK_COUNT }}
          Grype Count: ${{ steps.scans.outputs.GRYPE_COUNT }}
          Trivy Count: ${{ steps.scans.outputs.TRIVY_COUNT }}
          Image ID: ${{ matrix.images }}
          For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Post to slack when things fail.
      if: ${{ failure()  }}
      uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
      env:
        SLACK_ICON: http://github.com/chainguardian.png?size=48
        SLACK_USERNAME: chainguardian
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: james-test-channel
        SLACK_COLOR: '#8E1600'
        MSG_MINIMAL: 'true'
        SLACK_TITLE: Releasing ${{ github.repository }} failed.
        SLACK_MESSAGE: |
          For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
