on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:

  example_matrix:
    strategy:
      matrix:
        images: ["nginx:1.19"]
    runs-on: ubuntu-latest
    steps:
      - uses: strongjz/actions/vul-scans@be0c3f6c4f9d651ac413d7915694b4e80aaf72e3
        id: scans
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.images }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          UPLOAD_GITHUB_CODE: true

      - if: ${{ steps.scans.outputs.TRIVY_COUNT != '0' || steps.scans.outputs.GRYPE_COUNT != '0' || steps.scans.outputs.SNYK_COUNT != '0'  }}
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        with:
          image: ${{ env.IMAGE }}
        env:
          SLACK_ICON: http://github.com/chainguardian.png?size=48
          SLACK_USERNAME: chainguardian
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: james-test-channel
          SLACK_COLOR: '#8E1600'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: Releasing ${{ github.repository }} failed.
          SLACK_MESSAGE: |
            Snyk Count: $${{ steps.scans.outputs.snyk }}
            Grype Count $${{ steps.scans.outputs.grype }}
            Trivy Count $${{ steps.scans.outputs.trivy }}
            Image ID: ${{ env.IMAGE }}
            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # Post to slack when things fail.
      - if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_ICON: http://github.com/chainguardian.png?size=48
          SLACK_USERNAME: chainguardian
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: james-test-channel
          SLACK_COLOR: '#8E1600'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: Testing Vulnerability scans failed.
          SLACK_MESSAGE: |
            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
