on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:

  example_matrix:
    strategy:
      matrix:
        images: ["vulhub/nginx:1.4.2", "vulhub/nginx:1.13.2", "vulhub/activemq:5.11.1"]
    runs-on: ubuntu-latest
    steps:
      - uses: strongjz/actions/vul-scans@ba7b3765ff9225ec31b3c45a454844538a2acb6f
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.images }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          UPLOAD_GITHUB_CODE: true

      # Post to slack when things fail.
      - if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_ICON: http://github.com/chainguardian.png?size=48
          SLACK_USERNAME: chainguardian
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: james-test-channel
          SLACK_COLOR: '#8E1600'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: Testing Vulnerability scans failed.
          SLACK_MESSAGE: |
            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
